// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Tab: typeof import('./components/Tab.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
  }
}

export {}
